package org.apache.kafka.common.metrics;

import org.apache.kafka.clients.CommonClientConfigs;
import org.junit.Assert;

import java.util.Map;

/**
 * Test class to verify a MetricsReporter configured for a consumer will receive the auto-generated consumer client id.
 */
public class AutoGeneratedConsumerClientIdTestMetricsReporter extends FakeMetricsReporter{

    @Override
    public void configure(Map<String, ?> configs) {
        Assert.assertTrue(configs.get(CommonClientConfigs.CLIENT_ID_CONFIG).toString().contains("consumer"));
    }
}
