package org.apache.kafka.common.metrics;

import org.apache.kafka.clients.CommonClientConfigs;
import org.junit.Assert;

import java.util.Map;

/**
 * Test class to verify a MetricsReporter configured for a producer will receive the auto-generated producer client id.
 */
public class AutoGeneratedProducerClientIdTestMetricsReporter extends FakeMetricsReporter {

    @Override
    public void configure(Map<String, ?> configs) {
        Assert.assertTrue(configs.get(CommonClientConfigs.CLIENT_ID_CONFIG).toString().contains("producer"));
    }
}

