package org.apache.kafka.common.metrics;

import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.apache.kafka.common.serialization.StringSerializer;
import org.junit.Test;

import java.util.Properties;

public class MetricsReporterTest {
    @Test
    public void testProducerAutoGeneratedClientId() {
        Properties props = new Properties();
        props.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9999");
        props.setProperty(ProducerConfig.METRIC_REPORTER_CLASSES_CONFIG, AutoGeneratedProducerClientIdTestMetricsReporter.class.getName());

        KafkaProducer<String, String> producer = new KafkaProducer<>(
                props, new StringSerializer(), new StringSerializer());

        producer.close();
    }

    @Test
    public void testConsumerAutoGeneratedClientId() {
        Properties props = new Properties();
        props.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9999");
        props.setProperty(ConsumerConfig.METRIC_REPORTER_CLASSES_CONFIG, AutoGeneratedConsumerClientIdTestMetricsReporter.class.getName());

        KafkaConsumer<String, String> consumer = new KafkaConsumer<>(
                props, new StringDeserializer(), new StringDeserializer());

        consumer.close();
    }

    @Test
    public void testUserSpecifiedClientId() {
        // producer user specified client id
        Properties producerProps = new Properties();
        producerProps.setProperty(ProducerConfig.CLIENT_ID_CONFIG, "user-specified");
        producerProps.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9999");
        producerProps.setProperty(ProducerConfig.METRIC_REPORTER_CLASSES_CONFIG, UserSpecifiedClientIdTestMetricsReporter.class.getName());

        KafkaProducer<String, String> producer = new KafkaProducer<>(
                producerProps, new StringSerializer(), new StringSerializer());

        producer.close();

        // consumer user specified client id
        Properties consumerProps = new Properties();
        consumerProps.setProperty(ConsumerConfig.CLIENT_ID_CONFIG, "user-specified");
        consumerProps.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9999");
        consumerProps.setProperty(ConsumerConfig.METRIC_REPORTER_CLASSES_CONFIG, UserSpecifiedClientIdTestMetricsReporter.class.getName());

        KafkaConsumer<String, String> consumer = new KafkaConsumer<>(
                consumerProps, new StringDeserializer(), new StringDeserializer());

        consumer.close();
    }
}
